import random

print('Temos alguns numeros aleatorios com essa biblioteca \n')

a = int(input('Digite o primeiro algarismo: '))

b = int(input('Digite o segundo algarismo: '))


ramdomi = random.randint(a, b)

print("O primeiro algarismo digitado: {}".format(a))

print("O segundo algarismo digitado: {}".format(b))

print('Selecao no intervalo: ')
print(ramdomi)

print('Selecao no intervalo: ')
ramdomi = random.randint(a, b)
print(ramdomi)

print('Selecao no intervalo: ')
ramdomi = random.randint(a, b)
print(ramdomi)

print('Selecao no intervalo: ')
ramdomi = random.randint(a, b)
print(ramdomi)

print('Selecao no intervalo: ')
ramdomi = random.randint(a, b)
print(ramdomi)